<?php

namespace CPASimUSante\ItemSelectorBundle\Repository;

/**
 * MainConfigItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainConfigItemRepository extends \Doctrine\ORM\EntityRepository
{
}
