<?php

namespace CPASimUSante\ItemSelectorBundle\Repository;

/**
 * MainConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
